/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package image;

import javax.swing.JOptionPane;

/**
 *
 * @author duchuy
 */
public class giaipt3an extends javax.swing.JFrame {

    /**
     * Creates new form giaipt2an
     */
    public giaipt3an() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(90, 180, 64, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 180, 64, 30);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 60)); // NOI18N
        jLabel4.setText("{");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 70, 20, 160);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 30)); // NOI18N
        jLabel3.setText("phương trình ba ẩn");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 10, 350, 38);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/Webp.net-resizeimage.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 10, 390, 50);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel5.setText("y +");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 180, 42, 24);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel6.setText("x +");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 180, 30, 24);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(90, 120, 64, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(300, 180, 64, 30);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel7.setText("x +");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 130, 42, 24);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel8.setText("y+");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 120, 42, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(300, 120, 64, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(200, 120, 64, 30);

        jLabel9.setFont(new java.awt.Font("Herculanum", 0, 40)); // NOI18N
        jLabel9.setText("Kết Quả");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 270, 180, 80);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(40, 370, 470, 40);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(90, 240, 64, 30);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 60)); // NOI18N
        jLabel11.setText("{");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 140, 20, 160);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(200, 240, 64, 30);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10);
        jTextField10.setBounds(300, 240, 64, 30);

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel12.setText("y +");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(270, 240, 42, 24);

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel13.setText("x +");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(160, 240, 30, 24);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel10.setText("z=");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 120, 42, 30);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(410, 120, 64, 30);

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel14.setText("z=");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(380, 180, 42, 30);

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12);
        jTextField12.setBounds(410, 180, 64, 30);

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel15.setText("z=");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(380, 240, 42, 30);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13);
        jTextField13.setBounds(410, 240, 64, 30);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/nền.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        String input = jTextField2.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField1.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField2.setText("");  // Xóa nội dung
            jTextField2.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        String input = jTextField3.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField5.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField3.setText("");  // Xóa nội dung
            jTextField3.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        String input = jTextField5.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField6.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField5.setText("");  // Xóa nội dung
            jTextField5.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        String input = jTextField6.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField11.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField6.setText("");  // Xóa nội dung
            jTextField6.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String input = jTextField1.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField4.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField1.setText("");  // Xóa nội dung
            jTextField1.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
       String input = jTextField4.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField12.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField4.setText("");  // Xóa nội dung
            jTextField4.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        String input = jTextField8.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField9.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField8.setText("");  // Xóa nội dung
            jTextField8.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
       String input = jTextField9.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField10.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField9.setText("");  // Xóa nội dung
            jTextField9.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        String input = jTextField10.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField13.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField13.setText("");  // Xóa nội dung
            jTextField13.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        String input = jTextField11.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField2.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField11.setText("");  // Xóa nội dung
            jTextField11.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        String input = jTextField12.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField8.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField12.setText("");  // Xóa nội dung
            jTextField12.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
          try {
        // Lấy giá trị từ các jTextField
        double a1 = Double.parseDouble(jTextField3.getText().trim());
        double b1 = Double.parseDouble(jTextField5.getText().trim());
        double c1 = Double.parseDouble(jTextField6.getText().trim());
        double d1 = Double.parseDouble(jTextField11.getText().trim());

        double a2 = Double.parseDouble(jTextField2.getText().trim());
        double b2 = Double.parseDouble(jTextField1.getText().trim());
        double c2 = Double.parseDouble(jTextField4.getText().trim());
        double d2 = Double.parseDouble(jTextField12.getText().trim());

        double a3 = Double.parseDouble(jTextField8.getText().trim());
        double b3 = Double.parseDouble(jTextField9.getText().trim());
        double c3 = Double.parseDouble(jTextField10.getText().trim());
        double d3 = Double.parseDouble(jTextField13.getText().trim());

        // Gọi hàm giải phương trình bậc nhất ba ẩn
        double[] ketQua = pt3an.giaiPhuongTrinhBac1BaAn(a1, b1, c1, d1, a2, b2, c2, d2, a3, b3, c3, d3);

        // Xử lý nghiệm và hiển thị kết quả
        String result;
        if (Double.isNaN(ketQua[0])) {
            result = "Hệ phương trình vô nghiệm hoặc vô số nghiệm";
        } else {
            result = String.format("x = %.5f, y = %.5f, z = %.5f", ketQua[0], ketQua[1], ketQua[2]);
        }
        
        jTextField7.setText(result); // Hiển thị kết quả
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập số hợp lệ.");
        jTextField13.setText(""); // Xóa nội dung nhập sai
        jTextField13.requestFocus(); // Yêu cầu nhập lại từ jTextField13
    }
    }//GEN-LAST:event_jTextField13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giaipt3an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giaipt3an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giaipt3an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giaipt3an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giaipt3an().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
