/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package image;

import javax.swing.JOptionPane;

/**
 *
 * @author duchuy
 */
public class giaipt2an extends javax.swing.JFrame {

    /**
     * Creates new form giaipt2an
     */
    public giaipt2an() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(130, 180, 64, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 180, 64, 30);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 60)); // NOI18N
        jLabel4.setText("{");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 80, 20, 160);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 30)); // NOI18N
        jLabel3.setText("phương trình hai ẩn");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 10, 350, 38);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/Webp.net-resizeimage.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 10, 390, 50);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel5.setText("y =");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 180, 42, 24);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel6.setText("x +");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 180, 30, 24);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(130, 130, 64, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(340, 180, 64, 30);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel7.setText("x +");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 133, 42, 24);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel8.setText("y=");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 130, 42, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(340, 130, 64, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 130, 64, 30);

        jLabel9.setFont(new java.awt.Font("Herculanum", 0, 40)); // NOI18N
        jLabel9.setText("Kết Quả");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 270, 180, 80);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(40, 370, 470, 40);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/nền.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        String input = jTextField2.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField1.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField2.setText("");  // Xóa nội dung
            jTextField2.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        String input = jTextField3.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField5.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField3.setText("");  // Xóa nội dung
            jTextField3.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        String input = jTextField5.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField6.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField5.setText("");  // Xóa nội dung
            jTextField5.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        String input = jTextField6.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField2.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField6.setText("");  // Xóa nội dung
            jTextField6.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String input = jTextField1.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField4.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField1.setText("");  // Xóa nội dung
            jTextField1.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
       try {
        // Lấy giá trị từ các jTextField
        double a1 = Double.parseDouble(jTextField1.getText().trim());
        double b1 = Double.parseDouble(jTextField2.getText().trim());
        double c1 = Double.parseDouble(jTextField3.getText().trim());
        double a2 = Double.parseDouble(jTextField5.getText().trim());
        double b2 = Double.parseDouble(jTextField6.getText().trim());
        double c2 = Double.parseDouble(jTextField4.getText().trim());

        // Gọi hàm giải phương trình bậc nhất hai ẩn
        double[] ketQua = pt2an.giaiPhuongTrinhBac1HaiAn(a1, b1, c1, a2, b2, c2);

        // Xử lý nghiệm và hiển thị kết quả
        String result;
        if (Double.isNaN(ketQua[0])) {
            result = "Hệ phương trình vô nghiệm hoặc vô số nghiệm";
        } else {
            result = String.format("x = %.5f, y = %.5f", ketQua[0], ketQua[1]);
        }
        
        jTextField7.setText(result); // Hiển thị kết quả
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập số hợp lệ.");
        jTextField4.setText(""); // Xóa nội dung nhập sai
        jTextField4.requestFocus(); // Yêu cầu nhập lại từ jTextField4
    }
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giaipt2an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giaipt2an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giaipt2an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giaipt2an.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giaipt2an().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
