/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package image;

/**
 *
 * @author ACER
 */
import javax.swing.JOptionPane;
public class htgiac extends javax.swing.JFrame {

    /**
     * Creates new form menuhc
     */
    public htgiac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ketqua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        canha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        canhb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        chieucao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        canhc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 242, 224));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HÌNH TAM GIÁC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 320, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/lets-icons_back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("nhập cạnh a");

        ketqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketquaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KẾT QUẢ");

        canha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canhaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("nhập cạnh b");

        canhb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canhbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("nhập h");

        chieucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chieucaoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("nhập cạnh c");

        canhc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canhcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ketqua, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chieucao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(canhc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(canhb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(canha, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canhb, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(canhc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chieucao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ketqua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 360, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/hinhanh.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ketquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketquaActionPerformed
         try {
        double canhA = Double.parseDouble(canha.getText().trim());
        double canhB = Double.parseDouble(canhb.getText().trim());
        double canhC = Double.parseDouble(canhc.getText().trim());

        if (canhA <= 0 || canhB <= 0 || canhC <= 0) {
            ketqua.setText("Lỗi: Các cạnh phải lớn hơn 0!");
            return;
        }

        // Kiểm tra điều kiện tam giác hợp lệ
        if (canhA + canhB <= canhC || canhA + canhC <= canhB || canhB + canhC <= canhA) {
            ketqua.setText("Lỗi: Ba cạnh không tạo thành tam giác!");
            return;
        }

        // Tính chu vi tam giác
        double chuVi = canhA + canhB + canhC;
        String ketQuaText = "Chu vi: " + chuVi;

        // Kiểm tra xem chiều cao có được nhập hay không để tính diện tích
        if (!chieucao.getText().trim().isEmpty()) {
            double chieuCao = Double.parseDouble(chieucao.getText().trim());

            if (chieuCao <= 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập chiều cao lớn hơn 0!", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
                chieucao.setText(""); // Xóa nội dung nhập sai
            } else {
                double dienTich = (canhA * chieuCao) / 2;
                ketQuaText += ", Diện tích: " + dienTich;
            }
        }

        ketqua.setText(ketQuaText);
    } catch (NumberFormatException e) {
        ketqua.setText("Lỗi: Dữ liệu nhập vào không hợp lệ!");
    }
    }//GEN-LAST:event_ketquaActionPerformed

    private void canhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canhaActionPerformed
        try {
        double canhA = Double.parseDouble(canha.getText().trim());

        if (canhA <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập cạnh A lớn hơn 0!", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
            canha.setText(""); // Xóa nội dung nhập sai
            return;
        }

        ketquaActionPerformed(null);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập một số hợp lệ!", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
        canha.setText(""); // Xóa nếu nhập sai
    }
    }//GEN-LAST:event_canhaActionPerformed

    private void canhbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canhbActionPerformed
        try {
        double canhB = Double.parseDouble(canhb.getText().trim());

        if (canhB <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập cạnh B lớn hơn 0!", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
            canhb.setText(""); // Xóa nội dung nhập sai
            return;
        }

        ketquaActionPerformed(null);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập một số hợp lệ!", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
        canhb.setText(""); // Xóa nếu nhập sai
    }
    
    }//GEN-LAST:event_canhbActionPerformed

    private void canhcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canhcActionPerformed
        try {
        double canhC = Double.parseDouble(canhc.getText().trim());

        if (canhC <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập cạnh C lớn hơn 0!", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
            canhc.setText(""); // Xóa nội dung nhập sai
            return;
        }

        ketquaActionPerformed(null);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập một số hợp lệ!", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
        canhc.setText(""); // Xóa nếu nhập sai
    }
    }//GEN-LAST:event_canhcActionPerformed

    private void chieucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chieucaoActionPerformed
            try {
        if (!chieucao.getText().trim().isEmpty()) {
            double chieuCao = Double.parseDouble(chieucao.getText().trim());

            if (chieuCao <= 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập chiều cao lớn hơn 0!", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
                chieucao.setText(""); // Xóa nội dung nhập sai
                return;
            }
        }

        ketquaActionPerformed(null);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập một số hợp lệ!", "Lỗi nhập", JOptionPane.ERROR_MESSAGE);
        chieucao.setText(""); // Xóa nếu nhập sai
    }
    }//GEN-LAST:event_chieucaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menuhc muhc = new menuhc();
        muhc.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(htgiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(htgiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(htgiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(htgiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new htgiac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField canha;
    private javax.swing.JTextField canhb;
    private javax.swing.JTextField canhc;
    private javax.swing.JTextField chieucao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField ketqua;
    // End of variables declaration//GEN-END:variables
}
