/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package image;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author duchuy
 */
public class ptbac3 extends javax.swing.JFrame {

    /**
     * Creates new form ptbac2
     */
    public ptbac3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel8.setText("x³+");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 190, 53, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(100, 370, 470, 40);

        jLabel6.setFont(new java.awt.Font("Herculanum", 0, 40)); // NOI18N
        jLabel6.setText("Kết Quả");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 270, 180, 80);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(100, 190, 70, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/quay lại.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 40, 78, 40);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 190, 70, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(510, 190, 64, 40);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(380, 190, 70, 40);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel7.setText("x+");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 190, 60, 30);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel5.setText("x²+");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 190, 60, 30);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        jLabel1.setText("ax³+bx²+cx+d");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 50, 270, 45);

        jLabel2.setFont(new java.awt.Font("Academy Engraved LET", 3, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/Webp.net-resizeimage (2).png"))); // NOI18N
        jLabel2.setText("Kết Quả");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 40, 500, 470);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/hinhanh.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 660, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        String input = jTextField2.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField3.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField2.setText("");  // Xóa nội dung
            jTextField2.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        String input = jTextField3.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField1.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField3.setText("");  // Xóa nội dung
            jTextField3.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
            
        try {
    // Lấy giá trị nhập vào
    double a = Double.parseDouble(jTextField2.getText().trim());
    double b = Double.parseDouble(jTextField3.getText().trim());
    double c = Double.parseDouble(jTextField5.getText().trim());
    double d = Double.parseDouble(jTextField1.getText().trim());

    // Giải phương trình bậc 3
    double[] ketQua = pt3.giai3(a, b, c, d);
    
    String result;
    if (Double.isNaN(ketQua[0])) {
        result = "Vô nghiệm";
    } else if (Double.isNaN(ketQua[1])) {
        result = String.format("x = %.5f", ketQua[0]);
    } else if (Double.isNaN(ketQua[2])) {
        result = String.format("x1 = %.5f, x2 = %.5f", ketQua[0], ketQua[1]);
    } else {
        result = String.format("x1 = %.5f, x2 = %.5f, x3 = %.5f", ketQua[0], ketQua[1], ketQua[2]);
    }

    // Hiển thị kết quả
    jTextField4.setText(result);
   
    // Xóa toàn bộ dữ liệu nhập
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField5.setText("");

    // Đưa con trỏ nhập liệu về lại jTextField5
    jTextField5.requestFocus();
    
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập số hợp lệ.");
    jTextField1.setText(""); // Xóa nội dung nhập sai
    jTextField1.requestFocus(); // Yêu cầu nhập lại từ jTextField1
}


    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        String input = jTextField5.getText().trim();
        
        // Kiểm tra lỗi: Phải là số kiểu double hợp lệ
        try {
            Double.parseDouble(input); // Kiểm tra có phải số thực không
            jTextField2.requestFocus();  // Nếu hợp lệ, chuyển sang jTextField3
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Lỗi! Vui lòng nhập một số hợp lệ.");
            jTextField5.setText("");  // Xóa nội dung
            jTextField5.requestFocus();  // Đưa con trỏ về lại jTextField2
        }
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ptbac3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ptbac3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ptbac3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ptbac3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ptbac3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
